// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSd6JkInfc0tUv5KTjG3joZi0PtH_wX8',
    appId: '1:353846065263:web:6af10f159cc0e36d0e759a',
    messagingSenderId: '353846065263',
    projectId: 'gritdb',
    authDomain: 'gritdb.firebaseapp.com',
    storageBucket: 'gritdb.firebasestorage.app',
    measurementId: 'G-STLM78FE57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1BWjcYuxTnqEQujyQ5b6VPo3ZfayLBRk',
    appId: '1:353846065263:android:01ec035a268f38c70e759a',
    messagingSenderId: '353846065263',
    projectId: 'gritdb',
    storageBucket: 'gritdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrTb6GcStHFWctx7IHpfEFS8SjaWebgNY',
    appId: '1:353846065263:ios:2819068d87a20edf0e759a',
    messagingSenderId: '353846065263',
    projectId: 'gritdb',
    storageBucket: 'gritdb.firebasestorage.app',
    iosBundleId: 'com.example.grit',
  );
}
